name: Build Flutter Web
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.0-0.0.pre.1253'
          channel: 'master'
      - name: Clean project
        run: flutter clean
      - name: Get dependencies
        run: flutter pub get
      - name: Run Build tools
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Create Firebase options file
        run: echo ${{ secrets.FIREBASE_OPTIONS }} > lib/firebase_options.dart
      - name: Run Build Web
        run: flutter build web --release --base-href="/apps/quran-ayat/" --web-renderer=html
      - name: Deploy
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
